---
title: "Optimización de la supervivencia de las colonias de insectos"
author: "Sofía Palacios Cuevas, Martín Morales Trejo"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div style = "background-color:WhiteSmoke; color:black;padding:10px;">
<h5 style = "text-align-left"><strong>Resumen</strong></h5>
<p></p>
<p></p>
<p></p>
</div>

<h3 style = "text-align-left"><strong>Introducción</strong></h3>
<div align="justify">
<p>En este trabajo se utilizarán las ecuaciones diferenciales ordinarias para modelar la propagación / sobrevivencia de las colonias de insectos. El estudio de los ciclos de vida de las colonias ha dado pie a la creencia de que la colonia, aparentemente, maximiza el número de insectos reproductores al final de la temporada. Lo anterior permite que la colonia esparza sus genes, propagando así a los de su tipo en una moda óptima. Pueden considerarse diferentes modelos para el estudio de insectos hibernantes y no hibernantes. Sin embargo, el caso de los no hibernantes es más complejo debio a la necesidad de construir recursos substanciales y colmenas para sobrevivir al invierno.</p>
<p>A constinuación se considerará un modelo para una colinia en la que estudiamos dos tipos de insectos propios de la misma, obreros y reproductores (reinas). Sea $W(t)$ el número de insectos obreros en la colonia al tiempo $t$ (el cual se mide en días de la temporada), mientras que $Q(t)$ corresponde al número de insectos reproductores (reinas) en la colonia al tiempo $t$. Para este estudio, no vamos a suponer ninguna distinción de clase de edad.</p>
<p>Para estudiar las tazas de crecimiento de cada especie, se propone el siguiente modelo:</p></div>
<div align = "center"><p>$\frac{dQ(t)}{dt}=b \cdot c \cdot (1-u(t)) \cdot R(t) \cdot W(t) - v \cdot Q(t)$ </br>$\frac{dW(t)}{dt}=b \cdot u(t) \cdot R(t) \cdot W(t) - \mu \cdot W(t)$
</p></div>
<div align = "justify"><p>Como condiciones iniciales, usamos $W(0) = 1$ y $Q(0) = 0$ debido a que consideramos a la abeja reina fundadora como una obrera, puesto que ella busca alimento para la primera cría.</p>
<p>Existe también otra población a considerar: los zánganos. Éstos vienen de otras colmenas y son necesarios para fertilizar a las hembras. Una buena colmena durante la temporada de apareamiento puede tener entre 1 - 10 por ciento de zánganos que se reúnen diariamente en nubes que las reinas buscan para ser fecundadas. Las reinas se aparean con 5-20 zánganos y cada zángano muere después del apareamiento. Desafortunadamente, los zánganos no hacen otra cosa que comer miel. No recogen recursos, no defienden, no hacen cera ni cuidan de las crías. Normalmente, todos los zánganos son expulsados de la colmena al final de la temporada. Por lo tanto, en nuestro modelo, no los consideramos.</p>
</div></br>

<h5 style ="text-align-left"><strong> Descripción de las variables: </strong></h5>
| Variable | Descripción  |
|:--------:|:-------------|
| $R(t)$|Es la función de retorno (por unidad de miembro de la colonia) que representa la abundancia de recursos y la capacidad de forrajeo de la colonia en el momento t. La abundancia de recursos es muy importante para las abejas melíferas y no es en absoluto una constante. Se trata, pues, de una primera aproximación. Puede ser una medida de la diversidad floral en el caso de una colonia de abejas. A menudo se puede suponer que es constante, pero los modelos son bastante robustos y se aplican cuando $R(t)$ refleja más los cambios más amplios del ecosistema.|
| $-\mu W(t)$| Es un término de decaimiento exponencial que dice que, en ausencia de cualquier entrada de energía $(R(t))$, la población de obreras morirá. |
|$u(t)$|Es el porcentaje de utilización (entre 0 y 1) que la colonia aplica a la producción de las obreras. Volviendo a la ecuación de $Q(t)$ vemos que $(1 - u(t))$ representa entonces la parte (entre 0 y 1) del recurso que la colonia aplica a la producción de reproductores (reinas). |
|$b$|Significa un factor de conversión de la biomasa, es decir, de la energía del recurso, cuánto se convierte realmente en insectos trabajadores por unidad de tiempo.|
|$c$|representa un factor de conversión diferencial, es decir, si $c > 1$ se necesita más energía para producir un insecto reproductor que para producir un insecto trabajador y si $c = 1$ la energía necesaria para producir un insecto trabajador y uno reproductor es la misma. A menudo se asume este último caso. Mientras que para producir una reina se necesita más energía, por ejemplo, más cera para la célula (más grande) y más jalea real (probablemente el doble), para una reina es más grande, tanto como el doble de un insecto obrero. Pero la energía no es mucha en ambos casos.|
|$-vQ(t)$|Representa la decadencia exponencial de la población de reproductores en ausencia de otros aportes de energía. Nota: En el caso de las abejas melíferas, la población reproductora es básicamente de 1 ó 2. Producen varias reinas al mismo tiempo (de 2 a 8 aproximadamente) cuando se preparan para enjambrar. Pero las reinas "luchan" y sólo una sobrevive. No se sabe por qué hacen esto, pero se cree que es para gestionar el riesgo, ya que deben tener una (pero no más) que sobreviva o la colmena morirá. Esto se debe a que la madre de estas reinas suele salir en un enjambre una semana antes de este evento. Por lo tanto, tienes dos reinas supervivientes, una en casa y otra que se ha ido para empezar una nueva colmena. Esto puede repetirse varias veces en una temporada, por lo que puede haber hasta 4 reinas supervivientes (3 enjambres) al final de la temporada.|

<div align = "justify"><p>Otro factor es el inventario de miel. Cuando hay mucha, las abejas empiezan a cambiar de comportamiento. Se preparan para un enjambre y crían más abejas. Así que tal vez también se podría incluir un "Inventario" de recursos que se añade con los recursos disponibles de fuera de la colonia. Tal vez haya un umbral de inventario por encima del cual el comportamiento cambia. Otro factor es que un enjambre necesita suficientes abejas y miel para empezar una nueva colonia con éxito y dejar suficientes abejas (y crías) para ser viable. Una estimación aproximada es que el 50% de las abejas se van en un enjambre y el buen tamaño de la colonia antes de un enjambre es de unas 50.000 abejas. Aquí hay mucha variación.</p><p>Ahora la pregunta es la siguiente,</p>
</div>
<div align = "center">"¿Qué $u(t)$ debe utilizar la colonia para que el número de reproductores, $Q(T)$, al final de la temporada (cuando $t = T$) sea máximo?" </div></br>
<div align = "justify">La determinación de esta función $u(t)$ pertenece a una disciplina conocida como teoría del control óptimo. Se trata de una clase de problemas que tratan de encontrar el valor de T de forma que se optimice algún valor funcional, en este caso $Q(T)$, mientras está sujeto a algún sistema dinámico, en este caso las ecuaciones diferenciales $(1)$ con condiciones iniciales. </div></br>
<div align = "justify">Consideremos estos valores de los parámetros: $b = 0.0013$, $c = 1$, $\mu= 0.022$, $v = 0.005$, $T = 205$ días y $R(t) = 50$. Recordemos que $u(t)$ es una función (en este caso, llamada función de control admisible, en realidad) que está entre 0 y 1, donde $u(t) = 0$, significa que en el tiempo $t$ la colonia pone el 0% de sus energías en la producción de obreras; $u(t) = 1$, significa que en el tiempo $t$ la colonia pone el $100%$ de sus energías en la producción de obreras; y, por ejemplo, $u(140) = 0.31$, significa que en el tiempo $t= 140$ la colonia pone el $31%$ de sus energías en la producción de obreras.</div>


<h3 style = "text-align-left"><strong>Metodología</strong></h3></br>
<div align="justify">Para el presente trabajo, primero probaremos el modelo propuesto en $(1)$, usando diferentes $u(t)$. Para ello, primeramente graficaremos cada $u(t)$ en el intervalo $[0, 205]$. En segundo lugar, describiremos el comportamiento de la colonia. A continuación, calcularemos el número de insectos reina al final de la temporada y graficaremos ambos $Q(t)$ y $W(t)$ en el intervalo $[0, 205]$ - con variables identificadas. Posteriormente, propondremos una estrategia diferente, la cual modelaremos con una función $u(t)$. Finalmente, analizaremos nuestra propuesta de la misma forma que se hizo con el modelo propuesto por el profesor. </div></br>

<div align ="justify"><p>Se pasa de no criar ninguna reina a criar unas pocas. Sin embargo, hay demasiadas abejas para que dediquen toda su energía a criar reinas. Sólo se necesitan unas pocas abejas para criar reinas, digamos de 5 a 100 de 50.000. Probablemente se deba a la velocidad a la que una obrera puede producir jalea real y a la cantidad que necesita una reina. El resto de las abejas se ocupan de recoger más néctar, fabricar celdas de cera, rechazar a los intrusos, recoger polen, limpiar la colmena, etc. Así, otro modelo podría considerar que hay dos niveles de $u(t)$: bajo $(u(t) = 0)$ y alto $(u(t)0.0001\cdot W)$. Puede ser que la energía para hacer una reina no sea un gran problema. Tiene que ver más con el número de abejas, el inventario de miel, el inventario de crías, los niveles de recursos naturales, la temporada (se necesitan muchos zánganos de otras colmenas), la temperatura, etc. Ahora, ¿podemos determinar un tiempo de cambio óptimo t, cuando la colonia debe pasar de producir todos los insectos obreros $(u(t) = 1$ para $t< t_{s}$, por lo que $u(t) = 1 - UnitStep[t -t_{s}])$ a producir todos los reproductores (reinas) $(u(t) = 0$ para $t> t_{s})$?</p>
<p>a) Muestre cómo es la curva de $Q(T = 205)$ frente a $t_{s}$. Es decir, pruebe una serie de tiempos de conmutación, $t_{s}$ en el intervalo de tiempo $[0, 205]$ (en un rango amplio y en un rango estrecho sobre su valor óptimo, recoja los puntos de datos resultantes $(t_{s}, Q(205))$ en un conjunto, llamado datos, y grafique estos puntos para ver cuál podría ser un tiempo de conmutación óptimo. </p>
<p>b) Utilizando el tiempo de conmutación óptimo de la colonia que has descubierto en $(3)$, muestra cómo se compara con todos los resultados de la sección Modelo - ¡prueba! anterior y con tu propia estrategia en (2).</p></br><p>Explore el efecto en nuestra estrategia de optimización de $(3)$ si cambiamos nuestro valor de $c$ - recuerde cuál es el significado de c - vea arriba. Por ejemplo, supongamos que cambiamos nuestro problema de $c = 1$ a, digamos, $c = 2$, o $c= \frac{1}{2}$ (asegúrese de explicar lo que cada uno de estos significa en términos de la colonia y el modelo) entonces, ¿qué efecto tienen estos cambios en nuestro tiempo de conmutación óptima?</p></div>






